[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bunchor_template = "7LBeQpPgzzjEWw4z7S5aJF3zyyqMFpKfMn1hSg7DKxL9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 1000000 tests/*.test.ts"